### ISSUE TITLE
long delay to post new version on conda-forge

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/pangeo-dask-feedstock#43]
https://github.com/conda-forge/pangeo-dask-feedstock/blob/6d8d0129b174f5c39c7558b5e180b5098b001900/recipe/meta.yaml#L1

just noting that it's been over 6 hours since https://github.com/conda-forge/pangeo-dask-feedstock/pull/42 was merged bumping to version 2020.09.30, and I'm not seeing it on conda-forge... maybe there are just occasional longer delays than the typical 1-2 hours? cc @jhaman, @ocefpaf

**Comment by ocefpaf** [comment]
Looks like the job did not run on master. I just restarted it. See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=216292&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=c91ef11f-704a-5037-5b4b-afe1ed812384

**Comment by ocefpaf** [comment]
Just made to cf-staging. It will be available soon:

https://anaconda.org/cf-staging/pangeo-dask/files
